server {
    listen @@NGINX_PORT@@;
    listen [::]:@@NGINX_PORT@@;

    server_name @@SERVER_FQDN@@ @@SERVER_IP@@ localhost;

    client_max_body_size 25m;

    location /static/ {
        alias @@NETBOX_DIR@@/netbox/static/;
    }

    location / {
        proxy_pass http://127.0.0.1:@@GUNICORN_PORT@@;
        proxy_set_header X-Forwarded-Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
